version: "3.0"

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: bash -c "npm run migration && npm run start:dev"
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .dev.env     
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
